version: 2
registries:
  takumi_guard_pypi:
    type: python-index
    url: https://pypi.flatt.tech/simple/
    token: ${{secrets.TAKUMI_GUARD_TOKEN}}

updates:
  - package-ecosystem: uv
    directory: /
    registries:
      - takumi_guard_pypi
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
